apiVersion: "cilium.io/v1alpha1"
kind: TracingPolicy
metadata:
  name: "block-writing"
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Equal"
              values:
                - "/usr/bin/mkdir"
          matchActions:
            - action: Sigkill
        - matchArgs:
            - index: 0
              operator: "Equal"
              values:
                - "/usr/bin/touch"
          matchActions:
            - action: Sigkill
