apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mohammadhani18/labfrontend
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          value: "http://backend-api:5000"
        - name: ADMIN_URL
          value: "http://admin-api:5000" # Security issue: should not have access
        - name: ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: admin-secret
              key: admin-key

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
